export const REQUEST_POSTS = 'REQUEST_POSTS';
export const RECEIVE_POSTS = 'RECEIVE_POSTS';
export const ADD_POST = 'ADD_POST';
export const RECEIVE_DELETE_POST = 'RECEIVE_DELETE_POST';
export const RECEIVE_UPDATE_POST = 'RECEIVE_UPDATE_POST';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const REQUEST_COMMENTS = 'REQUEST_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const RECEIVE_DELETE_COMMENT = 'RECEIVE_DELETE_COMMENT';
export const RECEIVE_UPDATE_COMMENT = 'RECEIVE_UPDATE_COMMENT';

export const SEND_UPVOTE = 'SEND_UPVOTE';
export const RECEIVE_UPVOTE = 'RECEIVE_UPVOTE';
export const RECEIVE_VOTE_POST = 'RECEIVE_VOTE_POST';
export const RECEIVE_VOTE_COMMENT = 'RECEIVE_VOTE_COMMENT';

export const RECEIVE_SORT = 'RECEIVE_SORT';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
